source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               icons/
src.includes = src/,\
               META-INF/,\
               build.properties,\
               icons/
