source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/
src.includes = src/,\
               META-INF/,\
               build.properties,\
               plugin.xml
