package com.capellaagent.core.llm;

import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Data transfer object representing a single message in an LLM conversation.
 * <p>
 * Messages carry a {@link Role} that determines how the LLM treats the content,
 * along with optional metadata for tool-related interactions.
 */
public final class LlmMessage {

    /**
     * The role of the message sender in the conversation.
     */
    public enum Role {
        /** System-level instructions that guide the LLM's behavior. */
        SYSTEM,
        /** A message from the human user. */
        USER,
        /** A response generated by the LLM assistant. */
        ASSISTANT,
        /** The result of a tool invocation, returned to the LLM. */
        TOOL
    }

    private final Role role;
    private final String content;
    private final String toolCallId;
    private final String name;
    private final List<LlmToolCall> toolCalls;

    /**
     * Constructs a new LlmMessage.
     *
     * @param role       the role of the message sender; must not be null
     * @param content    the text content of the message; must not be null
     * @param toolCallId optional identifier linking this message to a tool call
     * @param name       optional name qualifier (e.g., tool function name)
     */
    public LlmMessage(Role role, String content, String toolCallId, String name) {
        this.role = Objects.requireNonNull(role, "role must not be null");
        this.content = Objects.requireNonNull(content, "content must not be null");
        this.toolCallId = toolCallId;
        this.name = name;
        this.toolCalls = null;
    }

    /**
     * Constructs a new LlmMessage with tool calls (used for assistant tool-call messages).
     *
     * @param role       the role of the message sender; must not be null
     * @param content    the text content of the message; must not be null
     * @param toolCallId optional identifier linking this message to a tool call
     * @param name       optional name qualifier
     * @param toolCalls  the list of tool calls; may be null
     */
    private LlmMessage(Role role, String content, String toolCallId, String name, List<LlmToolCall> toolCalls) {
        this.role = Objects.requireNonNull(role, "role must not be null");
        this.content = Objects.requireNonNull(content, "content must not be null");
        this.toolCallId = toolCallId;
        this.name = name;
        this.toolCalls = toolCalls != null ? List.copyOf(toolCalls) : null;
    }

    /**
     * Returns the role of this message.
     *
     * @return the message role
     */
    public Role getRole() {
        return role;
    }

    /**
     * Returns the text content of this message.
     *
     * @return the message content
     */
    public String getContent() {
        return content;
    }

    /**
     * Returns the tool call identifier, if present.
     *
     * @return an Optional containing the tool call ID, or empty
     */
    public Optional<String> getToolCallId() {
        return Optional.ofNullable(toolCallId);
    }

    /**
     * Returns the name qualifier, if present.
     *
     * @return an Optional containing the name, or empty
     */
    public Optional<String> getName() {
        return Optional.ofNullable(name);
    }

    // -- Factory methods for common message types --

    /**
     * Creates a system message.
     *
     * @param content the system prompt text
     * @return a new LlmMessage with SYSTEM role
     */
    public static LlmMessage system(String content) {
        return new LlmMessage(Role.SYSTEM, content, null, null);
    }

    /**
     * Creates a user message.
     *
     * @param content the user's input text
     * @return a new LlmMessage with USER role
     */
    public static LlmMessage user(String content) {
        return new LlmMessage(Role.USER, content, null, null);
    }

    /**
     * Creates an assistant message.
     *
     * @param content the assistant's response text
     * @return a new LlmMessage with ASSISTANT role
     */
    public static LlmMessage assistant(String content) {
        return new LlmMessage(Role.ASSISTANT, content, null, null);
    }

    /**
     * Creates a tool result message.
     *
     * @param toolCallId the identifier of the tool call this result belongs to
     * @param content    the JSON result content from the tool execution
     * @return a new LlmMessage with TOOL role
     */
    public static LlmMessage toolResult(String toolCallId, String content) {
        return new LlmMessage(Role.TOOL, content, toolCallId, null);
    }

    /**
     * Creates a tool result message with a named tool.
     *
     * @param toolCallId the identifier of the tool call
     * @param name       the function name of the tool
     * @param content    the JSON result content
     * @return a new LlmMessage with TOOL role
     */
    public static LlmMessage toolResult(String toolCallId, String name, String content) {
        return new LlmMessage(Role.TOOL, content, toolCallId, name);
    }

    /**
     * Creates an assistant message that carries tool calls (no text content).
     * <p>
     * This is used to persist the assistant's tool-call turn in the conversation
     * history so the LLM does not repeat the same calls.
     *
     * @param toolCalls the tool calls requested by the assistant
     * @return a new LlmMessage with ASSISTANT role and tool calls
     */
    public static LlmMessage assistantWithToolCalls(List<LlmToolCall> toolCalls) {
        return new LlmMessage(Role.ASSISTANT, "", null, null, toolCalls);
    }

    /**
     * Returns the list of tool calls attached to this message.
     *
     * @return the tool calls list; never null, may be empty
     */
    public List<LlmToolCall> getToolCalls() {
        return toolCalls != null ? toolCalls : Collections.emptyList();
    }

    /**
     * Checks whether this message carries tool calls.
     *
     * @return true if toolCalls is non-null and non-empty
     */
    public boolean hasToolCalls() {
        return toolCalls != null && !toolCalls.isEmpty();
    }

    @Override
    public String toString() {
        return "LlmMessage{role=" + role + ", content='" +
                (content.length() > 80 ? content.substring(0, 80) + "..." : content) +
                "', toolCallId=" + toolCallId + ", name=" + name + "}";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LlmMessage that = (LlmMessage) o;
        return role == that.role &&
                content.equals(that.content) &&
                Objects.equals(toolCallId, that.toolCallId) &&
                Objects.equals(name, that.name) &&
                Objects.equals(toolCalls, that.toolCalls);
    }

    @Override
    public int hashCode() {
        return Objects.hash(role, content, toolCallId, name, toolCalls);
    }
}
